### PR TITLE
Fix overflow error while checking filename extensions

### LINKED ISSUE #32: Tagged filenames that are too short crash `infer_format_tag`
## Description
`infer_format_tag` subtracts a filename's length from the length of an extension to use as an index, but if the filename is shorter than the extension this won't work. Since the sizes are unsigned, this results in an impossibly large index. This causes an out of bounds error that looks like this:

```
thread 'main' panicked at /home/almond/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ftag-0.3.3/src/load.rs:60:29:
byte index 18446744073709551615 is out of bounds of `*.sh`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    101011 IOT instruction (core dumped)  ftag tags
```

## Reproducing

This error can also be reproduced without using globbing, just by having a short filename.

file `ex`:
```
content of file doesn't matter
```

file `.ftag`:
```
[path]
ex
[tags]
example
```

Output of `ftag tags`:
```
thread 'main' panicked at /home/almond/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ftag-0.3.3/src/load.rs:60:29:
byte index 18446744073709551614 is out of bounds of `ex`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    101362 IOT instruction (core dumped)  ftag tags
```

Note: While making this minimal reproducible example I found that the same issue happens if the directory containing the files has a name too short.

### PR DESCRIPTION
**Pull request by almondheil**
Fixes #32

Tested on the minimal example I gave in that issue, as well as my larger tagged filesystem -- fixed all issues I had been having.

### CODE REVIEW

File: src/load.rs [hunk 1]
```diff
@@ -57,7 +57,7 @@ fn infer_format_tag(input: &str) -> impl Iterator<Item = String> + '_ {
     EXT_TAG_MAP.iter().filter_map(|(exts, tag)| {
         if exts
             .iter()
-            .any(|ext| input[input.len() - ext.len()..].eq_ignore_ascii_case(ext))
+            .any(|ext| str::ends_with(input, ext))
```
Comment (ranjeethmahankali) [inline src/load.rs:60]: Good catch!, My only concern is whether the comparison case sensitive? For example, I want to match "JPG" and "jpg".

**Review by ranjeethmahankali — CHANGES_REQUESTED** [review]

**Comment by ranjeethmahankali** [comment]
@almondheil Thank you for your interest in the project and opening PRs! I would love to hear more about how you use `ftag`.

File: src/load.rs (hunk 1 above)
Comment (ranjeethmahankali) [reply src/load.rs:60]: What about just computing the slice safely (by checking for bounds) and then using `eq_ignore_ascii_case`? There might be a slick Rust way of fixing this that I don't know of, that still keeps the case insensitivity.

**Comment by almondheil** [comment]
I see what you mean! Would something like this be what you want? Like you said, not an elegant Rust way but it actually ignores case.

**Review by ranjeethmahankali — APPROVED** [review]
